name: "The Zirconiac Speaks"
author: "The Zirconiac"
description: "A blog for The Zirconiac that talks about all things, but mostly electronics."
url: "http://zirconiacubed3v2.github.io"
plugins:
  - jekyll-sitemap
permalink: "/:title"
paginate: 6
paginate_path: "/:num"
google_site_verification: ihFGTiiJNSmqdD-mUmtYNIPk3Zr6WgOMFPppfMXvPvI
enable_google_verification: true
